name: Library Release

on:
  workflow_call:
    inputs:
      java-version:
        description: "Java version"
        required: false
        type: string
        default: "25"
      github-username:
        description: "GitHub username used for GitHub Packages authentication"
        required: true
        type: string
    secrets:
      GITHUB_PASSWORD:
        description: "GitHub token (PAT) used for release and GitHub Packages"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Java + Maven
        uses: quizup-organization/quizup-reusable-workflows/actions/setup-java-maven@main
        with:
          java-version: ${{ inputs.java-version }}
          server-username: ${{ inputs.github-username }}
          server-password: ${{ secrets.GITHUB_PASSWORD }}

      - name: Semantic Release
        id: release
        uses: quizup-organization/quizup-reusable-workflows/actions/semantic-release@main
        with:
          release-profile: maven
          github-token: ${{ secrets.GITHUB_PASSWORD }}

